fix(WO-45): generate_changelog.yml

diff --git a/.github/workflows/generate_changelog.yml b/.github/workflows/generate_changelog.yml
--- a/.github/workflows/generate_changelog.yml
+++ b/.github/workflows/generate_changelog.yml
@@ -54,17 +54,13 @@ jobs:
           if [ ! -f "CHANGELOG.md" ]; then
             echo "📝 CHANGELOG.md not found. Generating for the first time..."
             conventional-changelog -p angular -i CHANGELOG.md -s -r 1 --commit-path .
-            git add CHANGELOG.md
-            git commit -m "chore(changelog): generate initial changelog" || echo "No changes to commit"
-            git push origin HEAD:${{ github.ref_name }}
-            exit 0  # Exit early since changelog is now generated
-          fi
-
-          if git diff --name-only origin/production...HEAD | grep -q "CHANGELOG.md"; then
-            echo "✅ Changelog updated"
           else
-            echo "❌ ERROR: Changelog not updated. Please update CHANGELOG.md"
-            exit 1
+            if git diff --name-only origin/production...HEAD | grep -q "CHANGELOG.md"; then
+              echo "✅ Changelog updated"
+            else
+              echo "❌ ERROR: Changelog not updated. Please update CHANGELOG.md"
+              exit 1
+            fi
           fi
 
       - name: Push Changelog Updates
